name: build

on: [push,pull_request,workflow_dispatch]

jobs:
  Windows:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
    
    steps:
    - name: Download WinDeps
      run: wget https://github.com/MRVN-Radiant/MRVN-WinDeps/releases/download/v0.0/windeps.7z
      shell: powershell
    
    - uses: actions/checkout@v3
      with:
        submodules: recursive
  
    - name: Extract WinDeps
      uses: edgarrc/action-7z@v1
      with:
        args: 7z x windeps.7z -owindeps
  
    - name: Setup msvc
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup CMake
      run: cmake . -G "Ninja" - DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build .

    - name: Generate Artifact Name
      run: |
        echo "ARTIFACT_NAME=$(echo MRVN-Radiant_`date -u -Idate`_`git rev-parse --short HEAD`_Windows_${{ matrix.arch }})" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: install/
        if-no-files-found: error

  Linux:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install tools
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install mesa-common-dev qtbase5-dev
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup CMake
      run: cmake . -G "Unix Makefiles"

    - name: Build
      run: |
        cmake --build .

    - name: Generate Artifact Name
      run: |
        echo "ARTIFACT_NAME=$(echo MRVN-Radiant_`date -u -Idate`_`git rev-parse --short HEAD`_Linux_${{ matrix.arch }})" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: install/
        if-no-files-found: error
