name: build

on: [push,pull_request,workflow_dispatch]

jobs:
  windows-msys:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]
        cc: [gcc]
        include:
          - arch: x86
            msystem: MINGW32
            prefix: mingw-w64-i686

          - arch: x86_64
            msystem: MINGW64
            prefix: mingw-w64-x86_64

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: ${{ matrix.prefix }}-qt5-base ${{ matrix.prefix }}-libxml2 svn git
        msystem: ${{ matrix.msystem }}
        path-type: minimal
        release: false
        update: false

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup CMake
      run: cmake . -G "MinGW Makefiles"

    - name: Build
      run: cmake --build .

    - name: Install DLLs
      run: |
        wget https://www.dropbox.com/s/hcgkwzzmja3m6c0/netradiant-custom-extra-win.zip
        unzip -o netradiant-custom-extra-win.zip -d "install"

    - name: Generate Artifact Name
      run: |
        echo "ARTIFACT_NAME=$(echo MRVN-radiant_`date -u -Idate`_${GITHUB_SHA::7}_Windows_${{ matrix.arch }})" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: install/
        if-no-files-found: error

    - uses: actions/upload-artifact@v3
      with:
        name: warnings
        path: windows-warn*.log

  linux:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install tools
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install mesa-common-dev qtbase5-dev
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup CMake
      run: cmake . -G "Unix Makefiles"

    - name: Build
      run: |
        cmake --build .

    - name: Generate Artifact Name
      run: |
        echo "ARTIFACT_NAME=$(echo MRVN-radiant_`date -u -Idate`_${GITHUB_SHA::7}_Linux_${{ matrix.arch }})" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: install/
        if-no-files-found: error
